### ISSUE TITLE
#heroku

### ISSUE THREAD

**Issue by Incognito009** [reaitten/tk#1]
After deploying heroku get banned

**Comment by reaitten** [comment]
wasn't meant to be public, this was from an old repo from someone and it got removed, most likely heroku started banning the repository.

**Comment by AmirulAndalib** [comment]
LEL modify the code

**Comment by Incognito009** [comment]
What i change in script heroku not get banned my account

**Comment by reaitten** [comment]
> What i change in script heroku not get banned my account

modified code, you can try deploying again.

**Comment by AmirulAndalib** [comment]
> > What i change in script heroku not get banned my account
> 
> modified code, you can try deploying again.

bring latest version

**Comment by reaitten** [comment]
> > > What i change in script heroku not get banned my account
> > 
> > 
> > modified code, you can try deploying again.
> 
> bring latest version

ok

**Comment by reaitten** [comment]
> > > What i change in script heroku not get banned my account
> > 
> > 
> > modified code, you can try deploying again.
> 
> bring latest version

ok i updated

**Comment by AmirulAndalib** [comment]
KEK

**Comment by AmirulAndalib** [comment]
2021-05-03T03:49:10.172662+00:00 app[worker.1]: 
2021-05-03T03:49:10.466140+00:00 heroku[worker.1]: Process exited with status 1
2021-05-03T03:49:10.532234+00:00 heroku[worker.1]: State changed from up to crashed
2021-05-03T03:49:10.535932+00:00 heroku[worker.1]: State changed from crashed to starting
2021-05-03T03:49:29.191113+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c python3\ -m\ tortoolkit`
2021-05-03T03:49:29.943137+00:00 heroku[worker.1]: State changed from starting to up
2021-05-03T03:49:32.989237+00:00 app[worker.1]: 2021-05-03 09:19:32,988 INFO MainThread root Database created
2021-05-03T03:49:33.058025+00:00 app[worker.1]: 2021-05-03 09:19:33,057 INFO MainThread telethon.crypto.aes cryptg detected, it will be used for encryption
2021-05-03T03:49:34.335128+00:00 app[worker.1]: 2021-05-03 09:19:34,334 INFO MainThread pyrogram.crypto.aes Using TgCrypto
2021-05-03T03:49:37.093606+00:00 app[worker.1]: 2021-05-03 09:19:37,093 INFO MainThread root Telethon Client created.
2021-05-03T03:49:44.618866+00:00 app[worker.1]: 2021-05-03 09:19:44,618 INFO MainThread root Pryogram Client created.
2021-05-03T03:49:44.620369+00:00 app[worker.1]: Traceback (most recent call last):
2021-05-03T03:49:44.620370+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-05-03T03:49:44.620371+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-05-03T03:49:44.620371+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-05-03T03:49:44.620372+00:00 app[worker.1]:     exec(code, run_globals)
2021-05-03T03:49:44.620373+00:00 app[worker.1]:   File "/torapp/tortoolkit/__main__.py", line 44, in <module>
2021-05-03T03:49:44.620373+00:00 app[worker.1]:     add_handlers(ttkbot)
2021-05-03T03:49:44.620373+00:00 app[worker.1]:   File "/torapp/tortoolkit/core/HandleManager.py", line 38, in add_handlers
2021-05-03T03:49:44.620374+00:00 app[worker.1]:     chats=get_val("ALD_USR"))
2021-05-03T03:49:44.620374+00:00 app[worker.1]:   File "/torapp/tortoolkit/core/getVars.py", line 10, in get_val
2021-05-03T03:49:44.620374+00:00 app[worker.1]:     return SessionVars.get_var(variable)
2021-05-03T03:49:44.620375+00:00 app[worker.1]:   File "/torapp/tortoolkit/core/varholdern.py", line 54, in get_var
2021-05-03T03:49:44.620375+00:00 app[worker.1]:     val.extend(templi2)
2021-05-03T03:49:44.620376+00:00 app[worker.1]: AttributeError: 'set' object has no attribute 'extend'
2021-05-03T03:49:44.621436+00:00 app[worker.1]: Pyrogram v1.1.13, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-05-03T03:49:44.621437+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

**Comment by AmirulAndalib** [comment]
:(

**Comment by AmirulAndalib** [comment]
@reaitten i cant deploy to heroku after deploying its dead

**Comment by AmirulAndalib** [comment]
still error after latest patch :( 2021-05-03T04:14:23.145810+00:00 app[web.1]: Traceback (most recent call last):
2021-05-03T04:14:23.145811+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-05-03T04:14:23.145811+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2021-05-03T04:14:23.145812+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-05-03T04:14:23.145812+00:00 app[web.1]:     exec(code, run_globals)
2021-05-03T04:14:23.145813+00:00 app[web.1]:   File "/torapp/tortoolkit/__main__.py", line 44, in <module>
2021-05-03T04:14:23.145813+00:00 app[web.1]:     add_handlers(ttkbot)
2021-05-03T04:14:23.145814+00:00 app[web.1]:   File "/torapp/tortoolkit/core/HandleManager.py", line 38, in add_handlers
2021-05-03T04:14:23.145814+00:00 app[web.1]:     chats=get_val("ALD_USR"))
2021-05-03T04:14:23.145814+00:00 app[web.1]:   File "/torapp/tortoolkit/core/getVars.py", line 10, in get_val
2021-05-03T04:14:23.145815+00:00 app[web.1]:     return SessionVars.get_var(variable)
2021-05-03T04:14:23.145815+00:00 app[web.1]:   File "/torapp/tortoolkit/core/varholdern.py", line 51, in get_var
2021-05-03T04:14:23.145816+00:00 app[web.1]:     val.extend(templi2)
2021-05-03T04:14:23.145816+00:00 app[web.1]: AttributeError: 'set' object has no attribute 'extend'
2021-05-03T04:14:23.146521+00:00 app[web.1]: Pyrogram v1.1.13, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-05-03T04:14:23.146522+00:00 app[web.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-05-03T04:14:23.146522+00:00 app[web.1]: 
2021-05-03T04:14:23.487002+00:00 heroku[web.1]: Process exited with status 1
2021-05-03T04:14:23.977695+00:00 heroku[web.1]: State changed from up to crashed

**Comment by reaitten** [comment]
> still error after latest patch :(
> 2021-05-03T04:14:23.145810+00:00 app[web.1]: Traceback (most recent call last):
> 2021-05-03T04:14:23.145811+00:00 app[web.1]: File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> 2021-05-03T04:14:23.145811+00:00 app[web.1]: return _run_code(code, main_globals, None,
> 2021-05-03T04:14:23.145812+00:00 app[web.1]: File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
> 2021-05-03T04:14:23.145812+00:00 app[web.1]: exec(code, run_globals)
> 2021-05-03T04:14:23.145813+00:00 app[web.1]: File "/torapp/tortoolkit/**main**.py", line 44, in
> 2021-05-03T04:14:23.145813+00:00 app[web.1]: add_handlers(ttkbot)
> 2021-05-03T04:14:23.145814+00:00 app[web.1]: File "/torapp/tortoolkit/core/HandleManager.py", line 38, in add_handlers
> 2021-05-03T04:14:23.145814+00:00 app[web.1]: chats=get_val("ALD_USR"))
> 2021-05-03T04:14:23.145814+00:00 app[web.1]: File "/torapp/tortoolkit/core/getVars.py", line 10, in get_val
> 2021-05-03T04:14:23.145815+00:00 app[web.1]: return SessionVars.get_var(variable)
> 2021-05-03T04:14:23.145815+00:00 app[web.1]: File "/torapp/tortoolkit/core/varholdern.py", line 51, in get_var
> 2021-05-03T04:14:23.145816+00:00 app[web.1]: val.extend(templi2)
> 2021-05-03T04:14:23.145816+00:00 app[web.1]: AttributeError: 'set' object has no attribute 'extend'
> 2021-05-03T04:14:23.146521+00:00 app[web.1]: Pyrogram v1.1.13, Copyright (C) 2017-2021 Dan https://github.com/delivrance
> 2021-05-03T04:14:23.146522+00:00 app[web.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
> 2021-05-03T04:14:23.146522+00:00 app[web.1]:
> 2021-05-03T04:14:23.487002+00:00 heroku[web.1]: Process exited with status 1
> 2021-05-03T04:14:23.977695+00:00 heroku[web.1]: State changed from up to crashed

just wait, ill try to figure this out

**Comment by reaitten** [comment]
think it works now, can you try @AmirulAndalib

**Comment by AmirulAndalib** [comment]
broke sur

**Comment by AmirulAndalib** [comment]
i think you should leave all these behind and use my  0.2.1 beta repo {which is completely working on heroku with no blocks/errors} but the thing is Someone needs to merge the code properly and upgrade it to 0.2.4 beta .....

https://github.com/AmirulAndalib/timetorape

check out the repo and try to merge the code with the following conflicts

https://github.com/AmirulAndalib/timetorape/pull/1


i used meld to compare locked 0.2.4-beta with my 0.2.1 unlocked beta there are some changes to code but i dont understand which ones to merge where........

**Comment by reaitten** [comment]
> i think you should leave all these behind and use my 0.2.1 beta repo {which is completely working on heroku with no blocks/errors} but the thing is Someone needs to merge the code properly and upgrade it to 0.2.4 beta .....
> 
> https://github.com/AmirulAndalib/timetorape
> 
> check out the repo and try to merge the code with the following conflicts
> 
> [AmirulAndalib/timetorape#1](https://github.com/AmirulAndalib/timetorape/pull/1)
> 
> i used meld to compare locked 0.2.4-beta with my 0.2.1 unlocked beta there are some changes to code but i dont understand which ones to merge where........

sure ill try to merge, ill do it later since i cant do it right now.
thanks for telling me

**Comment by AmirulAndalib** [comment]
ok

**Comment by dr-qaatil** [comment]
you are doing a good job @reaitten ! request you to start from latest original source.
1.from your current work push execvarsample.py , heroku.yml and app.json
2. a lot less bugs to fix there shall be. i tried what i said just now. everything is working except for upload.

**Comment by reaitten** [comment]
> you are doing a good job @reaitten ! request you to start from latest original source.
> 1.from your current work push execvarsample.py , heroku.yml and app.json
> 2. a lot less bugs to fix there shall be. i tried what i said just now. everything is working except for upload.

i will try

**Comment by reaitten** [comment]
> > i think you should leave all these behind and use my 0.2.1 beta repo {which is completely working on heroku with no blocks/errors} but the thing is Someone needs to merge the code properly and upgrade it to 0.2.4 beta .....
> > https://github.com/AmirulAndalib/timetorape
> > check out the repo and try to merge the code with the following conflicts
> > [AmirulAndalib/timetorape#1](https://github.com/AmirulAndalib/timetorape/pull/1)
> > i used meld to compare locked 0.2.4-beta with my 0.2.1 unlocked beta there are some changes to code but i dont understand which ones to merge where........
> 
> sure ill try to merge, ill do it later since i cant do it right now.
> thanks for telling me

can you try now? bot works but i don't know why uploading isn't working

**Comment by AmirulAndalib** [comment]
> > > i think you should leave all these behind and use my 0.2.1 beta repo {which is completely working on heroku with no blocks/errors} but the thing is Someone needs to merge the code properly and upgrade it to 0.2.4 beta .....
> > > https://github.com/AmirulAndalib/timetorape
> > > check out the repo and try to merge the code with the following conflicts
> > > [AmirulAndalib/timetorape#1](https://github.com/AmirulAndalib/timetorape/pull/1)
> > > i used meld to compare locked 0.2.4-beta with my 0.2.1 unlocked beta there are some changes to code but i dont understand which ones to merge where........
> > 
> > 
> > sure ill try to merge, ill do it later since i cant do it right now.
> > thanks for telling me
> 
> can you try now? bot works but i don't know why uploading isn't working
haha thats the point its hard to fuck the code
but mine 0.2.1 beta unlocked works fine completely ......i think more bruteforce fuck is needed 🤓

**Comment by AmirulAndalib** [comment]
try a bit more bro @reaitten see my code and compare with original 0.2.4 beta remember its beta branch and not master so dont get mixed up

**Comment by reaitten** [comment]
> try a bit more bro @reaitten see my code and compare with original 0.2.4 beta remember its beta branch and not master so dont get mixed up

i tried my best, take a look again

**Comment by NickxFury** [comment]
Hey guys when the u update to the latest repo

**Comment by CurrentlyHidden** [comment]
Yup

**Comment by yourtulloh** [comment]
Lol

**Comment by AmirulAndalib** [comment]
> Lol

another dickhead

**Comment by yourtulloh** [comment]
> > Lol
> 
> another dickhead

You want i teach you kid?

**Comment by reaitten** [comment]
> Lol

ok
